version: "3.7"
services: 
  api:
    image: maslow123/books-api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file: ./.env
    ports:
      - "8080:8080"  
networks:
  books:
    driver: bridge